package com.user1.onboardingrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Identificador")
	private int id;
	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Apellido Paterno")
	private java.lang.String apellidoP;
	@org.kie.api.definition.type.Label(value = "Apellido Materno")
	private java.lang.String apellidoM;
	@org.kie.api.definition.type.Label(value = "Edad")
	private int edad;
	@org.kie.api.definition.type.Label(value = "Código Postal")
	private java.lang.String codigoPostal;
	@org.kie.api.definition.type.Label(value = "Puntaje Buro")
	private int puntajeBuro;
	@org.kie.api.definition.type.Label(value = "Credito Aprobado")
	private double credito;
	@org.kie.api.definition.type.Label(value = "Evaluacion")
	private int evaluacion;
	@org.kie.api.definition.type.Label(value = "Estado")
	private java.lang.String status;
	@org.kie.api.definition.type.Label(value = "Mensaje")
	private java.lang.String mensaje;

	public Solicitante() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellidoP() {
		return this.apellidoP;
	}

	public void setApellidoP(java.lang.String apellidoP) {
		this.apellidoP = apellidoP;
	}

	public java.lang.String getApellidoM() {
		return this.apellidoM;
	}

	public void setApellidoM(java.lang.String apellidoM) {
		this.apellidoM = apellidoM;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public java.lang.String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(java.lang.String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public int getPuntajeBuro() {
		return this.puntajeBuro;
	}

	public void setPuntajeBuro(int puntajeBuro) {
		this.puntajeBuro = puntajeBuro;
	}

	public double getCredito() {
		return this.credito;
	}

	public void setCredito(double credito) {
		this.credito = credito;
	}

	public int getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(int evaluacion) {
		this.evaluacion = evaluacion;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public Solicitante(int id, java.lang.String nombre,
			java.lang.String apellidoP, java.lang.String apellidoM, int edad,
			java.lang.String codigoPostal, int puntajeBuro, double credito,
			int evaluacion, java.lang.String status, java.lang.String mensaje) {
		this.id = id;
		this.nombre = nombre;
		this.apellidoP = apellidoP;
		this.apellidoM = apellidoM;
		this.edad = edad;
		this.codigoPostal = codigoPostal;
		this.puntajeBuro = puntajeBuro;
		this.credito = credito;
		this.evaluacion = evaluacion;
		this.status = status;
		this.mensaje = mensaje;
	}

}